[package]
name = "bytepath-rs"
version = "0.1.0"
authors = ["Dominic Bou-Samra <dominic.bou.samra@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.4.4"
specs = "0.14.3"
specs-derive = "0.4.0"
rand = "0.6.5"
nphysics2d = "0.10.3"
ncollide2d = "0.18.3"
nalgebra = "0.17.2"